// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDyFVbXW0c8iQMaypY-rWQbW-dENx_hIw',
    appId: '1:213630495762:web:119579fc3671e1c6573ccb',
    messagingSenderId: '213630495762',
    projectId: 'litbebe-a66b1',
    authDomain: 'litbebe-a66b1.firebaseapp.com',
    storageBucket: 'litbebe-a66b1.appspot.com',
    measurementId: 'G-M0X1ZJLS3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiWthdW9oA6TIm1vBJSCq83Q4IKRGdm7E',
    appId: '1:213630495762:android:80fe69e802f8d271573ccb',
    messagingSenderId: '213630495762',
    projectId: 'litbebe-a66b1',
    storageBucket: 'litbebe-a66b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jS7KB5jVGv4DvkmVfjmkttRdWPZTM3A',
    appId: '1:213630495762:ios:b1d88c7473aa624e573ccb',
    messagingSenderId: '213630495762',
    projectId: 'litbebe-a66b1',
    storageBucket: 'litbebe-a66b1.appspot.com',
    iosBundleId: 'com.example.litbebe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9jS7KB5jVGv4DvkmVfjmkttRdWPZTM3A',
    appId: '1:213630495762:ios:b1d88c7473aa624e573ccb',
    messagingSenderId: '213630495762',
    projectId: 'litbebe-a66b1',
    storageBucket: 'litbebe-a66b1.appspot.com',
    iosBundleId: 'com.example.litbebe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDyFVbXW0c8iQMaypY-rWQbW-dENx_hIw',
    appId: '1:213630495762:web:36a35811336114fb573ccb',
    messagingSenderId: '213630495762',
    projectId: 'litbebe-a66b1',
    authDomain: 'litbebe-a66b1.firebaseapp.com',
    storageBucket: 'litbebe-a66b1.appspot.com',
    measurementId: 'G-6JBL4K99BP',
  );
}
